### ISSUE TITLE
Python 3.8.0a1 can't install aiodns 2.0.0

### ISSUE THREAD

**Issue by notyeat** [saghul/aiodns#61]
my python version is 3.8.When I runing "python3 -m pip install aiodns" have a problem 'ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\notyeat\AppData\Local\Temp\pip-install-zoa6xiik\pycares\'

**Comment by saghul** [comment]
I'm going to need to more logs to diagnose this.

**Comment by notyeat** [comment]
this is error logs
```
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\msvc.py", line 489, in _find_latest_available_vc_ver
        return self.find_available_vc_vers()[-1]
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\notyeat\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\admin\AppData\Local\Temp\easy_install-gom5oip_\cffi-1.12.3\setup.py", line 127, in <module>
      File "C:\Users\admin\AppData\Local\Temp\easy_install-gom5oip_\cffi-1.12.3\setup.py", line 105, in uses_msvc
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\distutils\command\config.py", line 225, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\distutils\command\config.py", line 132, in _compile
        self.compiler.compile([src], include_dirs=include_dirs)
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\distutils\_msvccompiler.py", line 346, in compile
        self.initialize()
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\distutils\_msvccompiler.py", line 239, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\msvc.py", line 843, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\msvc.py", line 485, in __init__
        self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\admin\AppData\Local\Temp\pip-install-ok1q_mq9\pycares\setup.py", line 15, in <module>
        setup(name             = 'pycares',
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\__init__.py", line 142, in setup
        _install_setup_requires(attrs)
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\__init__.py", line 137, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\dist.py", line 583, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 778, in resolve
        dist = best[req.key] = env.best_match(
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 1063, in best_match
        return self.obtain(req, installer)
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 1075, in obtain
        return installer(requirement)
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\dist.py", line 653, in fetch_build_egg
        return cmd.easy_install(req)
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
        raise
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\admin\AppData\Local\Temp\easy_install-gom5oip_\cffi-1.12.3\setup.py", line 127, in <module>
      File "C:\Users\admin\AppData\Local\Temp\easy_install-gom5oip_\cffi-1.12.3\setup.py", line 105, in uses_msvc
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\distutils\command\config.py", line 225, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\distutils\command\config.py", line 132, in _compile
        self.compiler.compile([src], include_dirs=include_dirs)
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\distutils\_msvccompiler.py", line 346, in compile
        self.initialize()
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\distutils\_msvccompiler.py", line 239, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\msvc.py", line 843, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\msvc.py", line 485, in __init__
        self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
      File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\admin\AppData\Local\Temp\pip-install-ok1q_mq9\pycares\
```

**Comment by saghul** [comment]
Looks like you are missing the Visual Studio tools for building packages from source. You don't need this for Python 3.7 because you'll get a binary wheel, but for 3.8 you need to build it and thus requite the tools.

**Comment by VikasPoddar** [comment]
how to solve this issuse
