### ISSUE TITLE
Win 10 64bit

### ISSUE THREAD

**Issue by Tharuka1** [saghul/aiodns#88]

**Comment by Tharuka1** [comment]
From cffi callback <function _sock_state_cb at 0x000001CDF9068670>:
Traceback (most recent call last):
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\site-packages\pycares\__init__.py", line 91, in _sock_state_cb
    sock_state_cb(socket_fd, readable, writable)
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\site-packages\aiodns\__init__.py", line 104, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 504, in add_reader
    raise NotImplementedError
NotImplementedError
From cffi callback <function _sock_state_cb at 0x000001CDF9068670>:
Traceback (most recent call last):
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\site-packages\pycares\__init__.py", line 91, in _sock_state_cb
    sock_state_cb(socket_fd, readable, writable)
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\site-packages\aiodns\__init__.py", line 104, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 504, in add_reader
    raise NotImplementedError
NotImplementedError
From cffi callback <function _sock_state_cb at 0x000001CDF9068670>:
Traceback (most recent call last):
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\site-packages\pycares\__init__.py", line 91, in _sock_state_cb
    sock_state_cb(socket_fd, readable, writable)
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\site-packages\aiodns\__init__.py", line 104, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 504, in add_reader
    raise NotImplementedError
NotImplementedError
From cffi callback <function _sock_state_cb at 0x000001CDF9068670>:
Traceback (most recent call last):
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\site-packages\pycares\__init__.py", line 91, in _sock_state_cb
    sock_state_cb(socket_fd, readable, writable)
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\site-packages\aiodns\__init__.py", line 104, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 504, in add_reader
    raise NotImplementedError
NotImplementedError
From cffi callback <function _sock_state_cb at 0x000001CDF9068670>:
Traceback (most recent call last):
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\site-packages\pycares\__init__.py", line 91, in _sock_state_cb
    sock_state_cb(socket_fd, readable, writable)
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\site-packages\aiodns\__init__.py", line 104, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 504, in add_reader
    raise NotImplementedError
NotImplementedError
From cffi callback <function _sock_state_cb at 0x000001CDF9068670>:
Traceback (most recent call last):
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\site-packages\pycares\__init__.py", line 91, in _sock_state_cb
    sock_state_cb(socket_fd, readable, writable)
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\site-packages\aiodns\__init__.py", line 104, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 504, in add_reader
    raise NotImplementedError
NotImplementedError
From cffi callback <function _sock_state_cb at 0x000001CDF9068670>:
Traceback (most recent call last):
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\site-packages\pycares\__init__.py", line 91, in _sock_state_cb
    sock_state_cb(socket_fd, readable, writable)
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\site-packages\aiodns\__init__.py", line 104, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 504, in add_reader
    raise NotImplementedError
NotImplementedError
From cffi callback <function _sock_state_cb at 0x000001CDF9068670>:
Traceback (most recent call last):
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\site-packages\pycares\__init__.py", line 91, in _sock_state_cb
    sock_state_cb(socket_fd, readable, writable)
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\site-packages\aiodns\__init__.py", line 104, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 504, in add_reader
    raise NotImplementedError
NotImplementedError
From cffi callback <function _sock_state_cb at 0x000001CDF9068670>:
Traceback (most recent call last):
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\site-packages\pycares\__init__.py", line 91, in _sock_state_cb
    sock_state_cb(socket_fd, readable, writable)
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\site-packages\aiodns\__init__.py", line 104, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 504, in add_reader
    raise NotImplementedError
NotImplementedError
From cffi callback <function _sock_state_cb at 0x000001CDF9068670>:
Traceback (most recent call last):
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\site-packages\pycares\__init__.py", line 91, in _sock_state_cb
    sock_state_cb(socket_fd, readable, writable)
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\site-packages\aiodns\__init__.py", line 104, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "C:\Users\Tharuka\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 504, in add_reader
    raise NotImplementedError
NotImplementedError
