### ISSUE TITLE
AttributeError: module 'pycares' has no attribute 'QUERY_TYPE_CAA'

### ISSUE THREAD

**Issue by skupr-anaconda** [saghul/aiodns#97]
When building aiodns 3.0.0 with `conda build` on linux64 there is an error:

`AttributeError: module 'pycares' has no attribute 'QUERY_TYPE_CAA'`

Logs:

```
Packaging aiodns
INFO:conda_build.build:Packaging aiodns
INFO conda_build.build:build(2274): Packaging aiodns
Packaging aiodns-3.0.0-pyhd3eb1b0_2
INFO:conda_build.build:Packaging aiodns-3.0.0-pyhd3eb1b0_2
INFO conda_build.build:bundle_conda(1514): Packaging aiodns-3.0.0-pyhd3eb1b0_2
number of files: 10
Fixing permissions
Packaged license file/s.
INFO :: Time taken to mark (prefix)
        0 replacements in 0 files was 0.06 seconds
Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
WARNING:conda_build.build:Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
WARNING conda_build.build:bundle_conda(1687): Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
TEST START: output-artifacts/noarch/aiodns-3.0.0-pyhd3eb1b0_2.tar.bz2
Renaming work directory '/tmp/build/80754af9/aiodns_1620994560220/work' to '/tmp/build/80754af9/aiodns_1620994560220/work_moved_aiodns-3.0.0-pyhd3eb1b0_2_noarch'
INFO:conda_build.utils:Renaming work directory '/tmp/build/80754af9/aiodns_1620994560220/work' to '/tmp/build/80754af9/aiodns_1620994560220/work_moved_aiodns-3.0.0-pyhd3eb1b0_2_noarch'
INFO conda_build.utils:shutil_move_more_retrying(2077): Renaming work directory '/tmp/build/80754af9/aiodns_1620994560220/work' to '/tmp/build/80754af9/aiodns_1620994560220/work_moved_aiodns-3.0.0-pyhd3eb1b0_2_noarch'
shutil.move(work)=/tmp/build/80754af9/aiodns_1620994560220/work, dest=/tmp/build/80754af9/aiodns_1620994560220/work_moved_aiodns-3.0.0-pyhd3eb1b0_2_noarch)
INFO:conda_build.utils:shutil.move(work)=/tmp/build/80754af9/aiodns_1620994560220/work, dest=/tmp/build/80754af9/aiodns_1620994560220/work_moved_aiodns-3.0.0-pyhd3eb1b0_2_noarch)
INFO conda_build.utils:shutil_move_more_retrying(2084): shutil.move(work)=/tmp/build/80754af9/aiodns_1620994560220/work, dest=/tmp/build/80754af9/aiodns_1620994560220/work_moved_aiodns-3.0.0-pyhd3eb1b0_2_noarch)
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /tmp/build/80754af9/aiodns_1620994560220/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl


The following NEW packages will be INSTALLED:

    _libgcc_mutex:    0.1-main              defaults                                   
    aiodns:           3.0.0-pyhd3eb1b0_2    file:///tmp/build/80754af9/output-artifacts
    ca-certificates:  2021.4.13-h06a4308_1  defaults                                   
    cffi:             1.14.5-py39h261ae71_0 defaults                                   
    ld_impl_linux-64: 2.33.1-h53a641e_7     defaults                                   
    libffi:           3.3-he6710b0_2        defaults                                   
    libgcc-ng:        9.1.0-hdf63c60_0      defaults                                   
    libstdcxx-ng:     9.1.0-hdf63c60_0      defaults                                   
    ncurses:          6.2-he6710b0_1        defaults                                   
    openssl:          1.1.1k-h27cfd23_0     defaults                                   
    pycares:          3.1.1-py39h27cfd23_0  defaults                                   
    pycparser:        2.20-py_2             defaults                                   
    python:           3.9.4-hdb3f193_0      defaults                                   
    readline:         8.1-h27cfd23_0        defaults                                   
    sqlite:           3.35.4-hdfb4753_0     defaults                                   
    tk:               8.6.10-hbc83047_0     defaults                                   
    tzdata:           2020f-h52ac0ba_0      defaults                                   
    xz:               5.2.5-h7b6447c_0      defaults                                   
    zlib:             1.2.11-h7b6447c_3     defaults                                   

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
export PREFIX=/tmp/build/80754af9/aiodns_1620994560220/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
export SRC_DIR=/tmp/build/80754af9/aiodns_1620994560220/test_tmp
INFO: activate-binutils_linux-64.sh made the following environmental changes:
+ADDR2LINE=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-addr2line
+AR=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-ar
+AS=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-as
+CXXFILT=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-c++filt
+ELFEDIT=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-elfedit
+GPROF=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-gprof
+HOST=x86_64-conda_cos6-linux-gnu
+LD_GOLD=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-ld.gold
+LD=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-ld
+NM=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-nm
+OBJCOPY=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-objcopy
+OBJDUMP=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-objdump
+RANLIB=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-ranlib
+READELF=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-readelf
+SIZE=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-size
+STRINGS=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-strings
+STRIP=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-strip
INFO: activate-gcc_linux-64.sh made the following environmental changes:
+CC=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-cc
+CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/aiodns-3.0.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+CMAKE_PREFIX_PATH=:$PREFIX:/tmp/build/80754af9/aiodns_1620994560220/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/usr
+_CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
+CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -I$PREFIX/include
+CPP=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-cpp
+DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/aiodns-3.0.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -I$PREFIX/include
+GCC_AR=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-gcc-ar
+GCC_NM=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-gcc-nm
+GCC=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-gcc
+GCC_RANLIB=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-gcc-ranlib
+LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib
INFO: activate-gxx_linux-64.sh made the following environmental changes:
+CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/aiodns-3.0.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+CXX=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-c++
+DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/aiodns-3.0.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+GXX=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-g++
INFO: deactivate-gxx_linux-64.sh made the following environmental changes:
-CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/aiodns-3.0.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
-CXX=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-c++
-DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/aiodns-3.0.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
-GXX=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-g++
INFO: deactivate-gcc_linux-64.sh made the following environmental changes:
-CC=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-cc
-CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/aiodns-3.0.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
-CMAKE_PREFIX_PATH=:$PREFIX:/tmp/build/80754af9/aiodns_1620994560220/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/usr
-_CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
-CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -I$PREFIX/include
-CPP=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-cpp
-DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/aiodns-3.0.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
-DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -I$PREFIX/include
-GCC_AR=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-gcc-ar
-GCC_NM=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-gcc-nm
-GCC=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-gcc
-GCC_RANLIB=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-gcc-ranlib
-LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib
INFO: deactivate-binutils_linux-64.sh made the following environmental changes:
-ADDR2LINE=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-addr2line
-AR=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-ar
-AS=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-as
-CXXFILT=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-c++filt
-ELFEDIT=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-elfedit
-GPROF=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-gprof
-LD_GOLD=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-ld.gold
-LD=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-ld
-NM=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-nm
-OBJCOPY=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-objcopy
-OBJDUMP=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-objdump
-RANLIB=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-ranlib
-READELF=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-readelf
-SIZE=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-size
-STRINGS=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-strings
-STRIP=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-strip
Traceback (most recent call last):
  File "/tmp/build/80754af9/aiodns_1620994560220/test_tmp/run_test.py", line 2, in <module>
import: 'aiodns'
    import aiodns
  File "/tmp/build/80754af9/aiodns_1620994560220/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.9/site-packages/aiodns/__init__.py", line 28, in <module>
    'CAA'   : pycares.QUERY_TYPE_CAA,
AttributeError: module 'pycares' has no attribute 'QUERY_TYPE_CAA'
Tests failed for aiodns-3.0.0-pyhd3eb1b0_2.tar.bz2 - moving package to /tmp/build/80754af9/broken
WARNING:conda_build.build:Tests failed for aiodns-3.0.0-pyhd3eb1b0_2.tar.bz2 - moving package to /tmp/build/80754af9/broken
WARNING conda_build.build:tests_failed(2956): Tests failed for aiodns-3.0.0-pyhd3eb1b0_2.tar.bz2 - moving package to /tmp/build/80754af9/broken
TESTS FAILED: aiodns-3.0.0-pyhd3eb1b0_2.tar.bz2
```

**Comment by saghul** [comment]
Have you built pycares against the system c-ares? What version?

**Comment by skupr-anaconda** [comment]
In test environment we have:
pycares:          3.1.1-py39h27cfd23_0  defaults  

I see that we need to update it to 4.0.0

**Comment by saghul** [comment]
Not sure why it didn't fail at install time, aiodns 3.0.0 requires pycares 4.0.0, which does have CAA support.
